app/request/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField, DecimalField, SelectField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Optional

class RequestForm(FlaskForm):
    """Form for creating a new request."""
    item = TextAreaField('Item*(required)', validators=[DataRequired('Please enter the item'), Length(1, 500)])
    quantity = IntegerField('Quantity*', validators=[DataRequired('Please enter the quantity (only numbers are allowed)')])
    unit_price = DecimalField('Unit Price*', validators=[DataRequired('Please enter the price per unit (only numbers are allowed)')])
    total_cost = DecimalField('Total price*', validators=[DataRequired('Please enter the total price (only numbers are allowed)')])
    funding_source = SelectField('Funding*', choices=[('Expense', 'Expense'), ('MAARRF', 'MAARRF'), ('Grant', 'Grant'), ('SARA', 'SARA'), ('KOCH', 'KOCH'), ('Other', 'Other')], validators=[DataRequired('Please select the funding source')])
    funding_source_description = StringField('Funding Other')
    justification = TextAreaField('Justification*(required)', validators=[DataRequired('You must enter a justification for your request'), Length(1, 500)])

    # Updated field
    division = StringField('Division')
    grant_name = StringField('Grant Name')
    project_name = StringField('Project Name')


    # Vendor fields
    request_vendor_dropdown = SelectField('Vendor', validators=[Optional()], choices=[('default', 'Select Vendor or Enter new Vendor below'), ('1', 'Vendor 1'), ('2', 'Vendor 2')])
    request_vendor_name = StringField('Vendor Name', validators=[Length(5), Optional()])
    request_vendor_address = StringField('Vendor Address', validators=[Length(5), Optional()])
    request_vendor_phone = StringField('Vendor Phone')
    request_vendor_fax = StringField('Vendor Fax')
    request_vendor_email = StringField('Email', validators=[Email(), Optional()])
    request_vendor_taxid = StringField('Vendor Tax ID')
    request_vendor_mwbe = BooleanField('mwbe')
    request_vendor_enable = BooleanField('Vendor Enable')

    submit = SubmitField('Submit Request')

    def __init__(self, *args, **kwargs):
        """Fill the vendor dropdown with values from the database upon initialization"""
        super(RequestForm, self).__init__(*args, **kwargs)

        from ..models import Vendor
        vendors = Vendor.query.filter_by(enabled=True).order_by(Vendor.name).all()
        vendor_dropdown = [
            (0, 'Select Vendor or Enter New Vendor Below')
        ]
        for vendor in vendors:
            vendor_dropdown.append((vendor.id, vendor.name))
        self.request_vendor_dropdown.choices = vendor_dropdown

    def validate(self, extra_validators=None):
        if not FlaskForm.validate(self):
            print(self.errors)  # Print form errors
            return False

        # Check if user selected other and filled out the field
        if self.funding_source.data == "Other" and not self.funding_source_description.data:
            self.funding_source.errors.append("You must specify if you entered Other")
            return False

        return True

class EditRequestForm(FlaskForm):
    """Form for editing an existing request."""
    # assuming same fields as RequestForm
    item = TextAreaField('Item*(required)', validators=[DataRequired('Please enter the item'), Length(1, 500)])
    quantity = IntegerField('Quantity*', validators=[DataRequired('Please enter the quantity (only numbers are allowed)')])
    unit_price = DecimalField('Unit Price*', validators=[DataRequired('Please enter the price per unit (only numbers are allowed)')])
    total_cost = DecimalField('Total price*', validators=[DataRequired('Please enter the total price (only numbers are allowed)')])
    funding_source = SelectField('Funding*', choices=[('Expense', 'Expense'), ('MAARRF', 'MAARRF'), ('Grant', 'Grant'), ('SARA', 'SARA'), ('KOCH', 'KOCH'), ('Other', 'Other')], validators=[DataRequired('Please select the funding source')])
    funding_source_description = StringField('Funding Other')
    justification = TextAreaField('Justification*(required)', validators=[DataRequired('You must enter a justification for your request'), Length(1, 500)])

    # Updated field
    division = StringField('Division')
    grant_name = StringField('Grant Name')
    project_name = StringField('Project Name')

    # Vendor fields
    request_vendor_dropdown = SelectField('Vendor', validators=[Optional()], choices=[('default', 'Select Vendor or Enter new Vendor below'), ('1', 'Vendor 1'), ('2', 'Vendor 2')])
    request_vendor_name = StringField('Vendor Name', validators=[Length(5), Optional()])
    request_vendor_address = StringField('Vendor Address', validators=[Length(5), Optional()])
    request_vendor_phone = StringField('Vendor Phone')
    request_vendor_fax = StringField('Vendor Fax')
    request_vendor_email = StringField('Email', validators=[Email(), Optional()])
    request_vendor_taxid = StringField('Vendor Tax ID')
    request_vendor_mwbe = BooleanField('mwbe')
    request_vendor_enable = BooleanField('Vendor Enable')

    submit = SubmitField('Submit Request')

    # Similar to RequestForm, fill the vendor dropdown with values from the database upon initialization
    def __init__(self, *args, **kwargs):
        """Fill the vendor dropdown with values from the database upon initialization"""
        super(EditRequestForm, self).__init__(*args, **kwargs)

        from ..models import Vendor
        vendors = Vendor.query.filter_by(enabled=True).order_by(Vendor.name).all()
        vendor_dropdown = [
            (0, 'Select Vendor or Enter New Vendor Below')
        ]
        for vendor in vendors:
            vendor_dropdown.append((vendor.id, vendor.name))
        self.request_vendor_dropdown.choices = vendor_dropdown

app/request/__init__.py
from flask import Blueprint

request_bp = Blueprint('request', __name__)

from . import views   # This will import views.py where you will use request_bp

app/request/views.py
from flask import render_template, redirect, url_for, jsonify, request
from flask_login import login_required, current_user
from . import request_bp
from ..models import Vendor, Request, Comment
from .forms import RequestForm
from .. import db
import datetime
import uuid
from werkzeug.utils import secure_filename
import os
from datetime import datetime
from werkzeug.urls import url_parse
from sqlalchemy.exc import OperationalError
from uuid import UUID
from flask import send_from_directory
from flask import request
from flask import current_app
from flask import render_template, redirect, url_for, flash
from .forms import EditRequestForm
from ..models import Request, Vendor
from app import db
from flask import send_from_directory
import os
from uuid import UUID
import re
from flask import abort
from flask_login import current_user, login_required


@request_bp.route('/update_status', methods=['POST'])
def update_status():
    # Your code to update the status
    ...


@request_bp.route('/')  # Define this as the root route
@request_bp.route('/requests')  # Define this as another route
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    per_page = 50  # change this to the number of items you want per page
    requests = Request.query.order_by(Request.date_submitted.desc()).paginate(
        page=page, per_page=per_page, error_out=False)
    return render_template('request/requests.html', requests=requests)


@request_bp.route('/new_request', methods=['GET', 'POST'])
@login_required
def new_request():
    form = RequestForm()

    # Set the division and creator_id fields based on the current user
    form.division.data = current_user.division
    vendors = Vendor.query.filter(Vendor.enabled == True).all()
    vendor_choices = [(str(vendor.id), vendor.name) for vendor in vendors]
    # Add the None option at the beginning
    vendor_choices.insert(
        0, ('none', 'Select Vendor or Enter New Vendor Below'))
    form.request_vendor_dropdown.choices = vendor_choices

    if form.validate_on_submit():
        # Get vendor_id based on whether a new vendor was created or an existing one selected
        if form.request_vendor_dropdown.data == 'none':
            new_vendor = Vendor(
                name=form.request_vendor_name.data,
                address=form.request_vendor_address.data,
                phone=form.request_vendor_phone.data,
                fax=form.request_vendor_fax.data,
                email=form.request_vendor_email.data,
                tax_id=form.request_vendor_taxid.data,
                mwbe=form.request_vendor_mwbe.data,
                enabled=True,
            )
            db.session.add(new_vendor)
            db.session.flush()  # This is needed to get the new vendor's ID
            vendor_id = new_vendor.id
        else:
            vendor_id = form.request_vendor_dropdown.data

        # Set grant_name and project_name to None if not provided
        grant_name = form.grant_name.data if form.grant_name.data else None
        project_name = form.project_name.data if form.project_name.data else None

        # Create new Request
        new_request = Request(
            division=current_user.division,
            item=form.item.data,
            quantity=form.quantity.data,
            unit_price=form.unit_price.data,
            total_cost=form.total_cost.data,
            funding_source=form.funding_source.data,
            funding_source_description=None,
            grant_name=grant_name,
            project_name=project_name,
            justification=form.justification.data,
            status="New",
            creator_id=current_user.id,
            vendor_id=vendor_id,
        )

        if new_request.funding_source == "Grant":
            new_request.grant_name = form.grant_name.data
            new_request.project_name = form.project_name.data
        elif new_request.funding_source == "Other":
            new_request.funding_source_description = form.funding_source_description.data

        db.session.add(new_request)
        db.session.commit()  # Commit the changes to add the request to the database

        return jsonify(success=True, request_id=str(new_request.id))

    current_date = datetime.now().strftime('%m/%d/%Y')
    # or the attribute that stores the user's name
    current_username = current_user.first_name
    current_division = current_user.division
    return render_template('request/new_request.html', form=form, current_date=current_date, current_username=current_username, current_division=current_division)


@request_bp.route('/get_vendor/<string:vendor_id>')
def get_vendor(vendor_id):
    # Convert the string vendor_id to a UUID
    vendor_id = UUID(vendor_id)

    vendor = Vendor.query.get(vendor_id)
    if vendor is not None:
        return jsonify({
            'name': vendor.name,
            'address': vendor.address,
            'phone': vendor.phone,
            'fax': vendor.fax,
            'email': vendor.email,
            'tax_id': vendor.tax_id,
            'mwbe': vendor.mwbe,
            'enabled': vendor.enabled,
        })
    else:
        return jsonify(error="Vendor not found"), 404


@request_bp.app_template_filter()
def truncate_by_words(s, num_words):
    words = s.split()
    if len(words) > num_words:
        words = words[:num_words]
        words.append('...')
    return ' '.join(words)


UPLOAD_FOLDER = os.path.join(os.getcwd(), 'app/uploads')


@request_bp.route('/request/<request_id>')
@login_required
def view_request(request_id):
    request_id_uuid = uuid.UUID(request_id)  # convert request_id to a UUID
    request = Request.query.get_or_404(request_id_uuid)
    vendor = Vendor.query.get_or_404(request.vendor_id)  # get vendor
    comments = Comment.query.filter_by(request_id=request_id_uuid).order_by(
        Comment.timestamp.desc()).all()  # get all comments ordered by timestamp
    return render_template('request/request.html', request=request, vendor=vendor, comments=comments)


@request_bp.route('/submit_comment', methods=['POST'])
@login_required
def submit_comment():
    if current_user.is_authenticated:
        request_id = uuid.UUID(request.form.get('request_id'))
        comment_content = request.form.get('comment')
        file = request.files.get('file')
        file_path = None

        if file:
            filename = secure_filename(file.filename)
            file_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(file_path)

        new_comment = Comment(
            id=str(uuid.uuid4()),  # Generate a new UUID for the comment
            request_id=request_id,
            user_id=current_user.id,
            timestamp=datetime.now(),
            content=comment_content,
            filepath=file_path  # filepath will be None if no file was attached
        )

        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('request.view_request', request_id=request_id))
    else:
        # handle unauthenticated user here, for example:
        return "User not authenticated", 403


def is_valid_uuid(uuid_string):
    pattern = re.compile(
        r'^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$')
    return bool(pattern.match(uuid_string))


@request_bp.route('/download/<string:comment_id>', methods=['GET'])
def download(comment_id):
    """Allows users to download files from comments"""
    if not is_valid_uuid(comment_id):
        abort(400, "Invalid UUID format")
    comment = Comment.query.get_or_404(UUID(comment_id))
    directory = current_app.config['UPLOAD_FOLDER']
    filename = os.path.basename(comment.filepath)
    return send_from_directory(directory, filename, as_attachment=True)


@request_bp.route('/edit_request/<request_id>', methods=['GET', 'POST'])
def edit_request(request_id):
    try:
        req = Request.query.get_or_404(request_id)
        vendor = Vendor.query.get_or_404(req.vendor_id)

        form = EditRequestForm(obj=req)
        form.request_vendor_dropdown.choices = [
            (v.id, v.name) for v in Vendor.query.all()]
        form.division.data = current_user.division
        current_date = datetime.now().strftime('%m/%d/%Y')
        current_username = current_user.first_name
        current_division = current_user.division

        if request.method == 'GET':
            form.request_vendor_dropdown.data = req.vendor_id

        if form.validate_on_submit():
            req.vendor_id = form.request_vendor_dropdown.data
            form.populate_obj(req)

            # Update the database fields based on the funding source
            if req.funding_source == "Grant":
                req.funding_source_description = None  # Set the description to None
            elif req.funding_source == "Other":
                req.grant_name = None  # Clear the grant name
                req.project_name = None  # Assuming you meant project name as grant description

            db.session.commit()
            flash('Request information updated successfully', 'success')
            return redirect(url_for('request.home'))

        return render_template('request/edit_request.html', req=req, vendor=vendor, form=form, current_date=current_date, current_username=current_username, current_division=current_division)

    except OperationalError as e:
        db.session.rollback()  # Rollback the session to a clean state
        print(f"Error: {e}")  # You can also use proper logging here
        flash("There was a problem connecting to the database. Please try again.", "danger")
        # Redirect back to the home as an example
        return redirect(url_for('request.home'))

app/templates/request/request.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
  <div class="page-header">
    <h1>Request ID</h1>
    <a
      class="btn btn-primary btn-small mb-3 mt-3"
      href="{{ url_for('request.edit_request', request_id=request.id) }}"
      >Edit Request</a
    >
    <!-- Button trigger modal -->
    <button
      type="button"
      class="btn btn-primary"
      data-toggle="modal"
      data-target="#myModal"
    >
      View Comments
    </button>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <div class="table-responsive">
          <table id="requests" class="table table-bordered table-striped">
            <colgroup>
              <col class="col-xs-2" />
              <col class="col-xs-4" />
            </colgroup>
            <tbody id="request-table">
              <tr>
                <th scope="row" colspan="2">Request Information</th>
              </tr>
              <tr>
                <th scope="row">Request ID:</th>
                <td>{{ request.id }}</td>
              </tr>
              <tr>
                <th scope="row">Requester:</th>
                <td>{{ request.creator_id }}</td>
              </tr>
              <tr>
                <th scope="row">Division:</th>
                <td>{{ request.division }}</td>
              </tr>
              <tr>
                <th scope="row">Item:</th>
                <td>{{ request.item }}</td>
              </tr>
              <tr>
                <th scope="row">Quantity:</th>
                <td>{{ request.quantity }}</td>
              </tr>
              <tr>
                <th scope="row">Unit Price:</th>
                <td>${{ request.unit_price }}</td>
              </tr>
              <tr>
                <th scope="row">Total Cost:</th>
                <td>${{ request.total_cost }}</td>
              </tr>
              <tr>
                <th scope="row">Funding Source:</th>
                <td>{{ request.funding_source }}</td>
              </tr>
              <tr>
                <th scope="row">Justification:</th>
                <td>{{ request.justification }}</td>
              </tr>
              <tr>
                <th scope="row">Status:</th>
                <td>
                  {{ request.status }}
                  <a
                    class="btn btn-primary btn-sm pull-right text-white float-right"
                    data-toggle="modal"
                    data-target="#update_status"
                    >Update</a
                  >
                </td>
              </tr>

              {% if request.funding_source == 'Grant' %}
              <tr>
                <th scope="row">Grant Name</th>
                <td>{{ request.grant_name }}</td>
              </tr>
              <tr>
                <th scope="row">Project Name:</th>
                <td>{{ request.project_name }}</td>
              </tr>
              {% elif request.funding_source == 'Other' %}
              <tr>
                <th scope="row">Funding Source Description</th>
                <td>{{ request.funding_source_description }}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <colgroup>
              <col class="col-xs-1" />
              <col class="col-xs-5" />
            </colgroup>
            <tbody id="vendor-table">
              <tr>
                <th scope="row" colspan="2">Vendor Information</th>
              </tr>
              <tr>
                <th scope="row">Name:</th>
                <td>{{ vendor.name }}</td>
              </tr>
              <tr>
                <th scope="row">Address:</th>
                <td>{{ vendor.address }}</td>
              </tr>
              <tr>
                <th scope="row">Phone:</th>
                <td>{{ vendor.phone }}</td>
              </tr>
              <tr>
                <th scope="row">Fax:</th>
                <td>{{ vendor.fax }}</td>
              </tr>
              <tr>
                <th scope="row">Email:</th>
                <td>{{ vendor.email }}</td>
              </tr>
              <tr>
                <th scope="row">Tax ID:</th>
                <td>{{ vendor.tax_id }}</td>
              </tr>
              <tr>
                <th scope="row">M/WBE:</th>
                <td>{{ '✅' if vendor.mwbe else '❌' }}</td>
              </tr>
            </tbody>
          </table>
          <a class="btn btn-primary btn-small" href="#"
            >Return to Request History</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

<div
  class="container-fluid"
  style="display: inline-block; width: 100%; margin-top: 5px"
>
  <div class="form-group col">
    <h3>Make a comment</h3>
    <form
      action="{{ url_for('request.submit_comment') }}"
      method="post"
      enctype="multipart/form-data"
    >
      <textarea
        id="comment"
        name="comment"
        rows="5"
        style="width: 40%"
        maxlength="500"
        class="form-control mb-3"
      ></textarea>

      <input type="file" id="file" name="file" class="mb-3" />

      <!-- Hidden input field for 'request_id' -->
      <input
        type="hidden"
        id="request_id"
        name="request_id"
        value="{{ request.id }}"
      />

      <div class="d-grid">
        <button class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>

<!-- Modal -->
{% include 'components/comments.html' %} {% endblock %}

app/templates/request/requests.html
{% extends 'base.html' %} {% block content %}

<div class="container mt-5">
  <div class="container-fluid mb-3">
    <h1 class="display-4">Request History</h1>
  </div>

  <div class="input-group mb-1">
    <input
      class="form-control"
      id="myInput"
      type="text"
      placeholder="Search.."
    />
  </div>

  <div class="table-responsive-sm mt-5">
    <table class="table table-bordered table-striped" id="myTable">
      <thead>
        <tr>
          <th>Request#</th>
          <th>Date Submmitted</th>
          <th>Division</th>
          <th>Description</th>
          <th>Status</th>
          <th>Total Cost</th>
          <th>Edit</th>
          <th>View</th>
        </tr>
      </thead>
      <tbody>
        {% for request in requests.items %}
        <tr>
          <th scope="row">{{ request.id }}</th>
          <td>{{ request.date_submitted }}</td>
          <td>{{ request.division }}</td>
          <td>{{ request.item | truncate_by_words(10) }}</td>
          <!-- use item as description -->
          <td>{{ request.status }}</td>
          <td>${{ request.total_cost }}</td>
          <td>
            <a
              class="btn btn-primary btn-sm"
              href="{{ url_for('request.edit_request', request_id=request.id) }}"
            >
              <i class="fas fa-edit"></i>Edit Request</a
            >
          </td>
          <td>
            <a
              href="{{ url_for('request.view_request', request_id=request.id) }}"
              class="btn btn-success btn-sm"
            >
              <i class="fas fa-eye"></i> View Request
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="pagination">
      {% if requests.has_prev %}
      <a
        class="btn btn-outline-info"
        href="{{ url_for('request.home', page=requests.prev_num) }}"
        >Previous</a
      >
      {% endif %} {% if requests.has_next %}
      <a
        class="btn btn-outline-info"
        href="{{ url_for('request.home', page=requests.next_num) }}"
        >Next</a
      >
      {% endif %}
    </div>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  document.addEventListener("DOMContentLoaded", (event) => {
    function myFunction() {
      var input, filter, table, tr, td, i, j, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td");
        for (j = 0; j < td.length; j++) {
          if (td[j]) {
            txtValue = td[j].textContent || td[j].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
              break;
            } else {
              tr[i].style.display = "none";
            }
          }
        }
      }
    }

    document.getElementById("myInput").addEventListener("keyup", myFunction);
  });
</script>
{% endblock %}

app/templates/request/success.html
good !